export const dichVuPage = {
  meta: {
    title: "Dịch vụ",
    description:
      "SoftBuild chuyên thiết kế Mobile App, phát triển AI, tự động hóa quy trình (Automation), thiết kế website và phần mềm doanh nghiệp tối ưu vận hành.",
  },
  hero: {
    bgText: "SOFTBUILD",
    title: "Thiết kế App, giải pháp AI, Tự động hóa và phát triển phần mềm doanh nghiệp",
    description:
      "SoftBuild Việt Nam mang đến hệ thống giải pháp số đầy đủ bao gồm Web, Mobile, AI và SaaS. Chúng tôi chú trọng biến những ý tưởng của bạn thành những sản phẩm công nghệ tối ưu nhất. Mỗi giải pháp đều được xây dựng với tính ứng dụng cao, giúp doanh nghiệp hoạt động hiệu quả. Chúng tôi hứa hẹn sẽ đem lại giá trị thực sự cho đối tác qua từng đoạn mã.",
    marqueeTags: [
      "Thiết kế App",
      "Phát triển AI",
      "Tự động hóa quy trình (Automation)",
      "Thiết kế website",
      "Phát triển phần mềm doanh nghiệp",
      "Phát triển phần mềm tùy chỉnh",
      "Phát triển phần mềm MVP",
      "Phát triển ứng dụng SaaS",
      "Vận hành và bảo trì",
      "Phát triển sản phẩm phần mềm",
      "Phát triển AI",
      "Dịch vụ IT Outsourcing",
      "Phát triển DevOps",
      "Dịch vụ tích hợp AI",
      "Phát triển IoT",
      "Dịch vụ thuê ngoài IT",
      "Thiết kế website thuê ngoài",
      "Phát triển Blockchain",
      "Thuê lập trình viên tại Việt Nam",
      "Dịch vụ Offshore Development",
    ],
    cubeFaces: {
      front:
        "/images/services/winterfrost/cube-faces/nha-trang-travel-website.png",
      right:
        "/images/services/winterfrost/cube-faces/greenscape-mobile-app.png",
      back:
        "/images/services/winterfrost/cube-faces/nova-paint-website.png",
      left:
        "/images/services/winterfrost/cube-faces/planora-mobile-app.png",
    },
    bgImage: "/images/brand/winterfrost/winterfrost-banner.jpg",
  },
  servicesList: {
    label: "Các dịch vụ của chúng tôi",
    headlineLight: "Phát triển phần mềm và",
    headlineDark: "tự động hóa AI",
    viewLabel: "Xem dịch vụ",
    description:
      "SoftBuild cung cấp giải pháp Website, App và AI toàn diện, giúp doanh nghiệp vượt qua rào cản số hóa. Chúng tôi cam kết tối ưu chi phí, nâng cao hiệu suất và bảo mật tối đa, tạo nền tảng vững chắc để bạn dẫn đầu thị trường.",
    items: [
      {
        slug: "thiet-ke-app",
        title: "Thiết kế App (Mobile & Web)",
        desc: "SoftBuild chuyên phát triển ứng dụng di động hiệu năng cao trên cả iOS và Android, giao diện UI/UX trực quan và bảo mật tối đa. Tương thích linh hoạt với hệ thống sẵn có, giúp doanh nghiệp kết nối khách hàng và bứt phá tăng trưởng.",
        img: "/images/services/winterfrost/mobile-app-development.webp",
      },
      {
        slug: "phat-trien-ai",
        title: "Giải pháp AI & Trợ lý ảo",
        desc: "SoftBuild giúp doanh nghiệp phân tích và khai thác dữ liệu thông minh qua các giải pháp AI và Machine Learning chuyên biệt. Từ AI Agents, LLM đến phân tích dự đoán, chúng tôi hỗ trợ tự động hóa các quy trình quyết định phức tạp nhằm tạo ra lợi thế cạnh tranh vượt trội.",
        img: "/images/services/winterfrost/ai-development.webp",
      },
      {
        slug: "tu-dong-hoa-quy-trinh",
        title: "Tự động hóa quy trình (Automation & RPA)",
        desc: "Giải pháp tự động hóa toàn diện quy trình vận hành và nghiệp vụ doanh nghiệp. Loại bỏ thao tác thủ công, liên thông dữ liệu đa nền tảng, giảm thiểu 95% sai sót và tiết kiệm tới 60% chi phí vận hành hàng tháng.",
        img: "/images/services/winterfrost/generative-ai-integration.webp",
      },
      {
        slug: "thiet-ke-website",
        title: "Thiết kế website chuẩn SEO",
        desc: "Website chuyên nghiệp phải là công cụ tạo ra lợi nhuận. Tại SoftBuild, chúng tôi xây dựng những nền tảng tốc độ cao, ổn định và tối ưu trải nghiệm người dùng. Từ giao diện đến tính năng, mọi chi tiết đều được tinh chỉnh để thúc đẩy chuyển đổi, giúp doanh nghiệp vận hành trơn tru và khẳng định vị thế thương hiệu.",
        img: "/images/services/winterfrost/web-application-development-v2.png",
      },
      {
        slug: "phat-trien-ung-dung-saas",
        title: "Phát triển ứng dụng SaaS",
        desc: "SoftBuild chuyên phát triển ứng dụng SaaS trên nền tảng đám mây, giải quyết triệt để bài toán bảo mật và khả năng mở rộng. Chúng tôi tối ưu hóa cấu trúc hệ thống để đảm bảo vận hành ổn định, giúp doanh nghiệp tiết kiệm chi phí hạ tầng và tạo nguồn doanh thu định kỳ bền vững.",
        img: "/images/services/winterfrost/saas-application-development.webp",
      },
      {
        slug: "van-hanh-va-bao-tri",
        title: "Vận hành và bảo trì",
        desc: "Chúng tôi hiểu rằng một hệ thống ổn định là yếu tố sống còn đối với một doanh nghiệp. SoftBuild chủ động bảo trì và cập nhật bảo mật để phần mềm của bạn luôn hoạt động tốt nhất có thể. Đội ngũ kỹ thuật sẵn sàng giải quyết nhanh chóng mọi vấn đề để quá trình làm việc của đơn vị không bị gián đoạn. Bạn có thể hoàn toàn yên tâm tập trung phát triển kinh doanh vì chúng tôi ở đây để bảo vệ hệ thống mỗi ngày.",
        img: "/images/services/winterfrost/software-maintenance-and-support.webp",
      },
      {
        slug: "phat-trien-phan-mem-doanh-nghiep",
        title: "Phát triển phần mềm doanh nghiệp",
        desc: "SoftBuild phát triển các hệ thống quản lý chuyên sâu, giải quyết triệt để mọi phức tạp trong vận hành. Chúng tôi tùy biến phần mềm theo quy trình riêng biệt của từng doanh nghiệp, giúp số hóa dữ liệu tập trung và bảo mật tuyệt đối. Đây là nền tảng vững chắc để bạn chuẩn hóa tổ chức và tối ưu hóa nguồn lực bền vững.",
        img: "/images/services/winterfrost/enterprise-software-development.webp",
      },
      {
        slug: "phat-trien-phan-mem-mvp",
        title: "Phát triển phần mềm MVP",
        desc: "SoftBuild giúp doanh nghiệp ra mắt sản phẩm nhanh chóng với quy trình phát triển MVP tinh gọn. Chúng tôi tập trung vào các tính năng cốt lõi để xác thực ý tưởng và thu thập phản hồi thực tế, giúp tối ưu ngân sách và giảm thiểu rủi ro trước khi đầu tư lớn. Đây là bước đệm thông minh để bạn khởi đầu hiệu quả và an toàn.",
        img: "/images/services/winterfrost/mvp-software-development.webp",
      },
      {
        slug: "dich-vu-it",
        title: "Dịch vụ IT",
        desc: "SoftBuild trực tiếp phân tích quy trình hiện tại để thay thế các thao tác thủ công bằng hệ thống phần mềm quản lý. Việc số hóa giúp dữ liệu được lưu trữ tập trung, giảm thiểu sai sót do con người và rút ngắn thời gian xử lý công việc. Doanh nghiệp sẽ nắm bắt được số liệu thực tế theo thời gian thực để đưa ra các quyết định điều hành chính xác, từ đó tối ưu hóa chi phí vận hành và nâng cao hiệu suất làm việc của nhân sự.",
        img: "/images/services/winterfrost/custom-software-solutions.webp",
      },
      {
        slug: "tu-van-chuyen-doi-so",
        title: "Tư vấn chuyển đổi số",
        desc: "Chúng tôi thực hiện thiết lập, vận hành và bảo trì toàn bộ hệ thống máy chủ, mạng nội bộ và các thiết bị kỹ thuật cho doanh nghiệp. SoftBuild áp dụng các tiêu chuẩn bảo mật và quy trình sao lưu định kỳ để ngăn chặn rủi ro mất mát thông tin hoặc xâm nhập trái phép. Hệ thống kỹ thuật được duy trì hoạt động liên tục giúp công việc không bị gián đoạn, đồng thời giúp doanh nghiệp giảm bớt chi phí tuyển dụng và quản lý đội ngũ nhân sự IT nội bộ.",
        img: "/images/services/winterfrost/generative-ai-integration.webp",
      },
      {
        slug: "phat-trien-devops",
        title: "Phát triển DevOps",
        desc: "SoftBuild cải thiện quy trình phát triển phần mềm nhờ vào giải pháp CI/CD tự động, giúp giảm thiểu thời gian giới thiệu sản phẩm xuống mức tối thiểu. Chúng tôi chú trọng vào việc xây dựng một hạ tầng đám mây an toàn và hệ thống giám sát liên tục 24/7 để đảm bảo ổn định.",
        img: "/images/services/winterfrost/devops-development.webp",
      },
      {
        slug: "phat-trien-iot",
        title: "Phát triển IoT",
        desc: "SoftBuild liên kết các thiết bị thông minh và thu thập thông tin giúp các doanh nghiệp cải thiện quy trình hoạt động. Chúng tôi chú trọng vào việc phát triển những giải pháp IoT an toàn và linh hoạt, cho phép bạn theo dõi dữ liệu theo thời gian thực. Bạn sẽ có một hệ sinh thái kết nối mạnh mẽ để đưa ra những quyết định dựa trên dữ liệu chính xác nhất.",
        img: "/images/services/winterfrost/iot-development.webp",
      },
      {
        slug: "phat-trien-blockchain",
        title: "Phát triển Blockchain",
        desc: "SoftBuild xây dựng giải pháp Blockchain phi tập trung giúp bảo mật dữ liệu tuyệt đối. Chúng tôi ứng dụng Smart Contract để tối ưu chi phí và loại bỏ hoàn toàn rủi ro trung gian. Đây là nền tảng vững chắc giúp bạn củng cố niềm tin khách hàng và bứt phá hiệu quả trong kỷ nguyên số.",
        img: "/images/services/winterfrost/blockchain-development.webp",
      },
    ],
  },
  howWeWork: {
    label: "Quy trình làm việc của SoftBuild",
    ctaLabel: "Nhận tư vấn lộ trình ngay!",
    ctaHref: "tel:+84971450454",
    steps: [
      {
        num: "01",
        badge: "Tiếp nhận",
        title: "Tiếp nhận và phân tích yêu cầu",
        desc: "Chúng tôi lắng nghe ý tưởng và phân tích bài toán kinh doanh của bạn để đề xuất giải pháp tối ưu nhất. Việc này giúp chúng tôi xác định rõ phạm vi và mục tiêu ngay từ đầu, từ đó dự án tránh được các lãng phí không đáng có.",
      },
      {
        num: "02",
        badge: "Lên chiến lược",
        title: "Kế hoạch và cam kết",
        desc: "Lộ trình triển khai được cụ thể với các cột mốc thời gian rõ ràng ngay sau khi ký kết hợp đồng. Doanh nghiệp sẽ luôn chủ động trong việc giám sát tiến độ và điều chỉnh kịp thời để phù hợp với xu hướng thị trường.",
      },
      {
        num: "03",
        badge: "Thiết kế",
        title: "Thiết kế giao diện UI/UX",
        desc: "Tập trung vào tính thẩm mỹ và hành vi người dùng thực tế, chúng tôi thiết kế những giao diện trực quan và phân luồng logic. Mục tiêu cốt lõi là mang lại trải nghiệm mượt mà, giúp tăng tỉ lệ chuyển đổi cho sản phẩm của bạn.",
      },
      {
        num: "04",
        badge: "Thực hiện",
        title: "Lập trình và tối ưu liên tục",
        desc: "Đội ngũ kỹ sư thực hiện code đến đâu, kiểm tra lỗi và chất lượng đến đó trên từng module. Quy trình này giúp phát hiện lỗi sớm và tối ưu hiệu suất ngay lập tức, đảm bảo sản phẩm cuối cùng luôn đạt độ ổn định và hoàn thiện cao nhất.",
      },
      {
        num: "05",
        badge: "Bàn giao",
        title: "Bàn giao và hỗ trợ bền vững",
        desc: "SoftBuild thực hiện chuyển giao công nghệ đầy đủ, hướng dẫn vận hành chi tiết và duy trì dịch vụ bảo trì định kỳ. Chúng tôi cam kết đồng hành dài lâu để hệ thống của bạn luôn vận hành an toàn và sẵn sàng mở rộng.",
      },
    ],
  },
  benefits: {
    label: "Vì sao nên chọn dịch vụ tại SoftBuild?",
    headline: "Giá trị khác biệt từ SoftBuild",
    items: [
      { num: "1", title: "Công nghệ tiên phong", desc: "Làm chủ AI, Blockchain và IoT để mang lại các giải pháp công nghệ hiện đại và đột phá nhất cho doanh nghiệp.", icon: "rocket" },
      { num: "2", title: "Phát triển tinh gọn", desc: "Ứng dụng mô hình MVP giúp ra mắt sản phẩm nhanh chóng, tiết kiệm tối đa thời gian và ngân sách đầu tư.", icon: "zap" },
      { num: "3", title: "Chất lượng tin cậy", desc: "Lập trình song song với quy trình kiểm tra chất lượng, đảm bảo hệ thống luôn vận hành ổn định và đạt độ hoàn thiện cao.", icon: "shield" },
      { num: "4", title: "Đối tác chiến lược", desc: "Chúng tôi không chỉ thiết kế mà còn cung cấp giải pháp dài hạn, đồng hành cùng sự tăng trưởng của doanh nghiệp.", icon: "handshake" },
      { num: "5", title: "Mở rộng linh hoạt", desc: "Cấu trúc phần mềm hiện đại, cho phép doanh nghiệp dễ dàng nâng cấp và mở rộng hệ thống theo từng giai đoạn kinh doanh.", icon: "expand" },
      { num: "6", title: "Bảo mật tuyệt đối", desc: "Thiết lập hệ thống bảo mật đa tầng, chúng tôi cam kết bảo vệ an toàn dữ liệu và thông tin của doanh nghiệp.", icon: "lock" },
      { num: "7", title: "Trải nghiệm tối ưu", desc: "Thiết kế UI/UX tinh tế, tập trung vào hành vi người dùng thực tế để thúc đẩy tỷ lệ chuyển đổi hiệu quả nhất.", icon: "sparkles" },
      { num: "8", title: "Lộ trình làm việc chuyên nghiệp", desc: "Quy trình làm việc rõ ràng, báo cáo tiến độ chi tiết giúp doanh nghiệp luôn chủ động nắm bắt mọi giai đoạn dự án.", icon: "route" },
      { num: "9", title: "Giá trị lợi nhuận", desc: "Các giải pháp mà chúng tôi đưa ra đều mang một mục tiêu. Đó là biến công nghệ thành một đòn bẩy để gia tăng lợi nhuận của doanh nghiệp.", icon: "chart" },
    ],
  },
  ctaBanner: {
    badge: "Liên hệ ngay!",
    headline: "Lựa chọn giải pháp phù hợp với doanh nghiệp của bạn",
    description:
      "Hãy để các kỹ sư của SoftBuild tư vấn giải pháp chính xác dựa trên nhu cầu thực tế và ngân sách của doanh nghiệp.",
    ctaLabel: "Nhận tư vấn miễn phí",
    ctaHref: "tel:+84971450454",
  },
  industries: {
    label: "Các lĩnh vực nổi bật",
    headlineLight: "SoftBuild cung cấp dịch vụ",
    headlineDark: "theo từng lĩnh vực đặc thù",
    ctaLabel: "Khám phá tất cả các lĩnh vực",
    items: [
      { slug: "thuong-mai-dien-tu", title: "Thương mại điện tử", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Thuong-mai-dien-tu-HomeNest-Viet-Nam.png" },
      { slug: "cong-nghe-tai-chinh", title: "Công nghệ tài chính", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Cong-nghe-tai-chinh-HomeNest-Viet-Nam.png" },
      { slug: "y-te", title: "Y tế", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Cham-soc-suc-khoe-HomeNest-Viet-Nam.png" },
      { slug: "tai-chinh-doanh-nghiep", title: "Tài chính doanh nghiệp", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Tai-chinh-doanh-nghiep-HomeNest-Viet-Nam.png" },
      { slug: "phan-mem-doanh-nghiep", title: "Phần mềm doanh nghiệp", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Phat-trien-phan-mem-doanh-nghiep-HomeNest-Viet-Nam.png" },
      { slug: "ban-le", title: "Bán lẻ", icon: "/images/migrated/homenest-software/wp-content/uploads/2026/04/Retail-Industries-Icon.png" },
      { slug: "bat-dong-san", title: "Bất động sản", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Bat-dong-san-HomeNest-Viet-Nam.png" },
      { slug: "van-tai-va-logistics", title: "Vận tải và Logistics", icon: "/images/migrated/homenest-com-vn/wp-content/uploads/2026/05/Linh-vuc-Van-tai-va-Logistics-HomeNest-Viet-Nam.png" },
      { slug: "giao-duc", title: "Giáo dục", icon: "/images/migrated/homenest-software/wp-content/uploads/2026/04/Education-Industries-Icon.png" },
    ],
  },
  caseStudies: {
    heading: "Các dự án tiêu biểu",
    viewAllLabel: "Xem thêm",
    viewAllHref: "/case-studies",
    items: [
      {
        slug: "app-nivora-connect",
        category: "Phát triển ứng dụng theo yêu cầu",
        title: "App Nivora Connect",
        tag: "Thiết kế App",
        cta: "Xem dự án",
        img: "/images/projects/nivora-connect/01-cover.webp?v=wf-20260726",
      },
      {
        slug: "app-grevia-lawn",
        category: "Phát triển ứng dụng theo yêu cầu",
        title: "App Grevia Lawn",
        tag: "Thiết kế App",
        cta: "Xem dự án",
        img: "/images/projects/app-grevia-lawn/01-anh-bia-du-an.webp?v=wf-grevia-pro-20260726",
      },
      {
        slug: "website-loomora-rugs",
        category: "Bán lẻ · Thương mại điện tử",
        title: "Website Loomora Rugs",
        tag: "Thiết kế Website",
        cta: "Xem dự án",
        img: "/images/projects/website-loomora-rugs/01-anh-bia-du-an.webp?v=wf-projects-pro-20260726",
      },
    ],
  },
  technology: {
    label: "Nền tảng công nghệ",
    headline: ["Công nghệ vận hành", "", "tại SoftBuild"] as [string, string, string],
  },
  faq: {
    label: "Các câu hỏi thường gặp",
    headline: ["Giải Đáp", "Mọi", "Thắc Mắc"] as [string, string, string],
    intro: "Những câu hỏi thường gặp được khách hàng đặt cho SoftBuild.",
    items: [
      { q: "SoftBuild mạnh ở lĩnh vực nào?", a: "Chúng tôi đặc biệt giỏi trong việc tạo ra phần mềm tùy chỉnh cho Web, App, SaaS và ứng dụng những công nghệ mới như AI, Blockchain, IoT. Tất cả giải pháp được xây dựng để giải quyết các vấn đề thực tiễn trong doanh nghiệp." },
      { q: "Quá trình làm việc tại SoftBuild kéo dài bao lâu?", a: "Thời gian thực hiện phụ thuộc vào quy mô của dự án. Tuy nhiên, với mô hình phát triển gọn nhẹ, chúng tôi có thể giúp bạn ra mắt phiên bản chính trong 4-8 tuần để kiểm tra thị trường sớm." },
      { q: "Tôi đã có hệ thống sẵn, SoftBuild có thể tích hợp AI vào không?", a: "Có thể chứ. Chúng tôi chuyên cung cấp dịch vụ lắp ghép AI và GenAI vào các nền tảng hiện tại để tự động hóa quy trình, tối ưu hóa dữ liệu và nâng cao hiệu quả mà không cần thay thế hết hệ thống cũ." },
      { q: "Làm thế nào tôi có thể tin tưởng vào chất lượng sản phẩm?", a: "SoftBuild áp dụng quy trình kiểm soát chất lượng rất chặt chẽ trong suốt quá trình lập trình. Việc kiểm tra liên tục trên mỗi module giúp phát hiện lỗi sớm và đảm bảo hệ thống hoạt động ổn định nhất khi bàn giao." },
      { q: "Chi phí dịch vụ được tính toán ra sao?", a: "Chi phí sẽ được tính minh bạch dựa trên phạm vi công việc, độ phức tạp của tính năng và yêu cầu về công nghệ. Chúng tôi luôn đưa ra lời khuyên tốt nhất để cân bằng giữa ngân sách và các mục tiêu kinh doanh của bạn." },
      { q: "SoftBuild có đảm bảo bảo mật thông tin dự án không?", a: "Chắc chắn rồi. Chúng tôi luôn ký hợp đồng bảo mật nghiêm ngặt trước khi nhận thông tin dự án. Quyền sở hữu trí tuệ và toàn bộ mã nguồn sẽ thuộc về khách hàng khi bàn giao." },
      { q: "Chính sách hỗ trợ sau bàn giao của SoftBuild như thế nào?", a: "Chúng tôi không chỉ bàn giao rồi thôi. Chúng tôi cung cấp dịch vụ bảo trì định kỳ, cập nhật bảo mật và hỗ trợ kỹ thuật 24/7 để đảm bảo hệ thống của bạn luôn hoạt động trơn tru và sẵn sàng mở rộng." },
    ],
  },
} as const;
